image: docker:latest
services:
- docker:dind

stages:
- build
- test
- release

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/mangash/manga-frontend .
    - docker push registry.gitlab.com/mangash/manga-frontend